name: Inspections

on:
  pull_request:
    branches:
      - "*"

jobs:
  php-cs-fixer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
            ref: ${{ github.head_ref }}
            fetch-depth: 0  # Ensures all branches are fetched

      - name: Set up Git Identity
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Set up Git Authorization
        env:
          ACCESS_TOKEN: ${{ secrets.AUTH_ACCESS_TOKEN }}
        run: |
          git config --global http.extraheader "AUTHORIZATION: bearer ${ACCESS_TOKEN}"

      - name: Run PHP CS Fixer
        uses: docker://oskarstark/php-cs-fixer-ga
        with:
            args: --config=.php-cs-fixer.dist.php --allow-risky=yes

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
            commit_message: Fix styling
            branch: ${{ github.head_ref }}
