name: Inspections

on:
  pull_request:
    branches:
      - "*"

jobs:
  php-cs-fixer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: Run PHP CS Fixer
        uses: docker://oskarstark/php-cs-fixer-ga
        with:
          args: --config=.php-cs-fixer.dist.php --allow-risky=yes
      - name: Set up Git credentials
        run: |
          echo "machine github.com" >> ~/.netrc
          echo "login github-actions[bot]" >> ~/.netrc
          echo "password ${{ secrets.AUTH_ACCESS_TOKEN }}" >> ~/.netrc
          git config --global credential.helper 'store --file ~/.netrc'
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Fix styling
        env:
          GITHUB_TOKEN: ${{ secrets.AUTH_ACCESS_TOKEN }}
